import type { AppState, PlayerState } from './types';
import {
  bundledSampleLabel,
  bundledSampleOtherStemUrl,
  bundledSampleVideoUrl,
  bundledSampleVocalsStemUrl,
} from './sampleMedia';

const players: PlayerState[] = [
  {
    id: 'lead',
    name: 'Lead Vocal',
    mediaKind: 'video',
    sourceLabel: bundledSampleLabel,
    mediaSourceUrl: bundledSampleVideoUrl,
    mediaSourcePath: null,
    audioCodec: 'opus',
    videoCodec: 'vp9',
    supportsTransparency: false,
    availableStems: [
      { id: 'original', label: 'Original mix', status: 'source', sourceUrl: bundledSampleVideoUrl },
      { id: 'vocals', label: 'Separated vocals', status: 'generated', sourceUrl: bundledSampleVocalsStemUrl },
      { id: 'other', label: 'Other stem', status: 'generated', sourceUrl: bundledSampleOtherStemUrl },
    ],
    activeStemId: 'original',
    pitchStatus: 'idle',
    pitchSourceUrl: null,
    durationSec: 96,
    positionSec: 18.4,
    isPlaying: false,
    isLocked: true,
    mixMode: 'solo',
    lineColor: '#ffe66d',
    lineWidth: 1,
    opacity: 0.9,
    zIndex: 3,
    width: 1120,
    height: 680,
    offsetX: 0,
    offsetY: 0,
    pitchPoints: [],
  },
  {
    id: 'harmony',
    name: 'Harmony',
    mediaKind: 'video',
    sourceLabel: bundledSampleLabel,
    mediaSourceUrl: bundledSampleVideoUrl,
    mediaSourcePath: null,
    audioCodec: 'opus',
    videoCodec: 'vp9',
    supportsTransparency: false,
    availableStems: [
      { id: 'original', label: 'Original mix', status: 'source', sourceUrl: bundledSampleVideoUrl },
      { id: 'vocals', label: 'Separated vocals', status: 'generated', sourceUrl: bundledSampleVocalsStemUrl },
      { id: 'other', label: 'Other stem', status: 'generated', sourceUrl: bundledSampleOtherStemUrl },
    ],
    activeStemId: 'original',
    pitchStatus: 'idle',
    pitchSourceUrl: null,
    durationSec: 96,
    positionSec: 18.4,
    isPlaying: false,
    isLocked: true,
    mixMode: 'mixed',
    lineColor: '#7bdff2',
    lineWidth: 0.9,
    opacity: 0.62,
    zIndex: 2,
    width: 1040,
    height: 640,
    offsetX: 44,
    offsetY: 30,
    pitchPoints: [],
  },
  {
    id: 'guitar',
    name: 'Guitar Guide',
    mediaKind: 'video',
    sourceLabel: bundledSampleLabel,
    mediaSourceUrl: bundledSampleVideoUrl,
    mediaSourcePath: null,
    audioCodec: 'opus',
    videoCodec: 'vp9',
    supportsTransparency: false,
    availableStems: [
      { id: 'original', label: 'Original mix', status: 'source', sourceUrl: bundledSampleVideoUrl },
      { id: 'vocals', label: 'Separated vocals', status: 'generated', sourceUrl: bundledSampleVocalsStemUrl },
      { id: 'other', label: 'Other stem', status: 'generated', sourceUrl: bundledSampleOtherStemUrl },
    ],
    activeStemId: 'original',
    pitchStatus: 'idle',
    pitchSourceUrl: null,
    durationSec: 96,
    positionSec: 11.2,
    isPlaying: false,
    isLocked: false,
    mixMode: 'muted',
    lineColor: '#ff8fab',
    lineWidth: 0.9,
    opacity: 0.45,
    zIndex: 1,
    width: 980,
    height: 600,
    offsetX: 88,
    offsetY: 58,
    pitchPoints: [],
  },
];

export const initialState: AppState = {
  players,
  timeScaleSec: 5,
  pitchRangeSemitones: 18,
  pitchStemPreferenceId: 'vocals',
  pitchCenterMode: 'adaptive',
  selectedPlayerId: players[0].id,
};